name: URL Health Check

on:
  deployment_status

jobs:
  check-urls:
    if: |
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.target_url, 'vercel.app')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment to stabilize
        run: sleep 45

      - name: Check URLs
        run: |
          BASE_URL="${{ github.event.deployment_status.target_url }}"
          URLS=(
            "$BASE_URL"
            "$BASE_URL/about"
            "$BASE_URL/blog/post/openai-models-explained"
          )
          
          for url in "${URLS[@]}"; do
            echo "Checking $url"
            curl --fail --silent --show-error -L "$url" || exit 1
          done 